# Generated by Django 5.1.1 on 2024-09-07 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                ("Data_id", models.AutoField(primary_key=True, serialize=False)),
                ("Image", models.ImageField(null=True, upload_to="media/")),
            ],
            options={
                "db_table": "upload",
            },
        ),
        migrations.CreateModel(
            name="Last_login",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Login_Time", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "last_login",
            },
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(help_text="user_name", max_length=50)),
                ("user_age", models.IntegerField(null=True)),
                (
                    "user_email",
                    models.EmailField(help_text="user_email", max_length=254),
                ),
                (
                    "user_password",
                    models.EmailField(help_text="user_password", max_length=50),
                ),
                (
                    "user_address",
                    models.TextField(help_text="user_address", max_length=100),
                ),
                (
                    "user_contact",
                    models.CharField(help_text="user_contact", max_length=15),
                ),
                ("user_image", models.ImageField(null=True, upload_to="media/")),
                ("Date_Time", models.DateTimeField(auto_now=True, null=True)),
                (
                    "User_Status",
                    models.TextField(default="pending", max_length=50, null=True),
                ),
                ("Otp_Num", models.IntegerField(null=True)),
                (
                    "Otp_Status",
                    models.TextField(default="pending", max_length=60, null=True),
                ),
                ("Last_Login_Time", models.TimeField(null=True)),
                ("Last_Login_Date", models.DateField(auto_now_add=True, null=True)),
                ("No_Of_Times_Login", models.IntegerField(default=0, null=True)),
                ("Message", models.TextField(max_length=250, null=True)),
                ("Phone_Number", models.TextField(max_length=250, null=True)),
            ],
            options={
                "db_table": "user_details",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("Feed_id", models.AutoField(primary_key=True, serialize=False)),
                ("Rating", models.CharField(max_length=100, null=True)),
                ("Review", models.CharField(max_length=225, null=True)),
                ("Sentiment", models.CharField(max_length=100, null=True)),
                ("datetime", models.DateTimeField(auto_now=True)),
                (
                    "Reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.usermodel",
                    ),
                ),
            ],
            options={
                "db_table": "feedback_details",
            },
        ),
    ]
