# Generated by Django 5.1.1 on 2024-09-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_delete_dataset_remove_feedback_reviewer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="user_password",
            field=models.TextField(help_text="user_password", max_length=50),
        ),
    ]
