# Generated by Django 5.1.1 on 2024-09-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_usermodel_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="Date_Time",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="Last_Login_Date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="Last_Login_Time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="Message",
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="No_Of_Times_Login",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="User_Status",
            field=models.TextField(default="pending", max_length=50, null=True),
        ),
    ]
