# Generated by Django 5.1.1 on 2024-09-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_usermodel_date_time_usermodel_last_login_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
