# Generated by Django 5.1.1 on 2024-09-10 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_usermodel_last_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="Date_Time",
        ),
        migrations.RemoveField(
            model_name="usermodel",
            name="Last_Login_Date",
        ),
        migrations.RemoveField(
            model_name="usermodel",
            name="Last_Login_Time",
        ),
        migrations.RemoveField(
            model_name="usermodel",
            name="Message",
        ),
        migrations.RemoveField(
            model_name="usermodel",
            name="No_Of_Times_Login",
        ),
        migrations.RemoveField(
            model_name="usermodel",
            name="User_Status",
        ),
    ]
