# Generated by Django 5.1.1 on 2024-09-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="user_password",
            field=models.CharField(help_text="user_password", max_length=128),
        ),
    ]
