# Generated by Django 5.1.1 on 2024-09-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_usermodel_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="password",
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="user_email",
            field=models.EmailField(help_text="user_email", max_length=254),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="user_password",
            field=models.EmailField(help_text="user_password", max_length=50),
        ),
    ]
