# Generated by Django 5.1.1 on 2024-09-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_remove_usermodel_password_alter_usermodel_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="user_password",
            field=models.TextField(help_text="user_password", max_length=50),
        ),
    ]
