# Generated by Django 5.1.1 on 2024-09-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_usermodel_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="user_status",
            field=models.TextField(default="pending", max_length=50, null=True),
        ),
    ]
