# Generated by Django 5.1.1 on 2024-09-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_usermodel_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="Message",
            field=models.TextField(max_length=250, null=True),
        ),
    ]
