# Generated by Django 5.1.1 on 2024-09-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_usermodel_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("contact", models.CharField(max_length=15)),
                ("Message", models.TextField(max_length=250, null=True)),
            ],
            options={
                "db_table": "contact_details",
            },
        ),
        migrations.RemoveField(
            model_name="usermodel",
            name="Message",
        ),
    ]
