# Generated by Django 5.1.1 on 2024-09-13 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_contact_remove_usermodel_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("Feed_id", models.AutoField(primary_key=True, serialize=False)),
                ("Rating", models.CharField(max_length=100, null=True)),
                ("Review", models.CharField(max_length=225, null=True)),
                ("Sentiment", models.CharField(max_length=100, null=True)),
                ("datetime", models.DateTimeField(auto_now=True)),
                (
                    "Reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.usermodel",
                    ),
                ),
            ],
            options={
                "db_table": "feedback_details",
            },
        ),
    ]
