# Generated by Django 5.1.1 on 2024-09-13 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="Sentiment",
        ),
    ]
